WITH ACT_WITH_JENNIFER AS (
SELECT P.NAME, COUNT(P.NAME) AS COUNT
FROM PEOPLE AS P
INNER JOIN CREW AS C1 ON P.PERSON_ID = C1.PERSON_ID
INNER JOIN CREW AS C2 ON C1.TITLE_ID = C2.TITLE_ID
INNER JOIN PEOPLE AS P2 ON C2.PERSON_ID = P2.PERSON_ID
WHERE P2.NAME = 'Jennifer Lawrence' AND C1.CATEGORY IN ("ACTOR" , "ACTRESS")
GROUP BY P.NAME
ORDER BY P.NAME
)
SELECT NAME
FROM ACT_WITH_JENNIFER
WHERE COUNT IN (SELECT COUNT FROM ACT_WITH_JENNIFER WHERE NAME = 'Jennifer Lawrence');