SELECT AVG(R.RATING) AS AVG_RATING_ROBERT
FROM RATINGS AS R
WHERE R.TITLE_ID IN (SELECT C.TITLE_ID
FROM PEOPLE AS P
LEFT JOIN CREW AS C
ON C.PERSON_ID = P.PERSON_ID
WHERE P.NAME = 'Robert Downey Jr.' AND C.CATEGORY = 'ACTOR');
