WITH ACTION_MOVIE_LIST AS(
SELECT T.TITLE_ID
FROM TITLES AS T
WHERE T.TITLE_TYPE = "MOVIE" AND
T.GENRES LIKE "%ACTION%" AND 
(T.PREMIERED BETWEEN 1991 AND 2000) AND
T.TITLE_ID IN (SELECT DISTINCT A.TITLE_ID FROM AKAS AS A WHERE A.REGION = "JP")
)
SELECT DISTINCT P.NAME
FROM CREW AS C
JOIN PEOPLE AS P ON C.PERSON_ID = P.PERSON_ID
WHERE C.CATEGORY = "ACTRESS" AND C.TITLE_ID IN (SELECT TITLE_ID FROM ACTION_MOVIE_LIST)
ORDER BY P.NAME;