WITH FIND_ROBERT AS (
SELECT DISTINCT C.TITLE_ID
FROM CREW AS C
JOIN PEOPLE AS P ON P.PERSON_ID = C.PERSON_ID 
WHERE P.NAME = "ROBERT DOWNEY JR."
)
SELECT COUNT(DISTINCT C.PERSON_ID) AS ACTRESS_WITH_ROBERT
FROM CREW AS C
WHERE C.CATEGORY = "ACTRESS" AND 
C.TITLE_ID IN  (SELECT * FROM FIND_ROBERT);






