SELECT DISTINCT P.NAME, P.BORN
FROM CREW AS C
JOIN TITLES AS T ON T.TITLE_ID = C.TITLE_ID
JOIN PEOPLE AS P ON P.PERSON_ID = C.PERSON_ID
WHERE C.CATEGORY = "ACTOR" AND  ((T.PREMIERED-P.BORN) BETWEEN 0 AND 20)
ORDER BY P.NAME;