SELECT P.NAME
FROM CREW AS C
LEFT JOIN RATINGS AS R ON C.TITLE_ID = R.TITLE_ID
LEFT JOIN PEOPLE AS P ON C.PERSON_ID = P.PERSON_ID
WHERE C.CATEGORY = 'COMPOSER' AND R.RATING > 8
GROUP BY C.PERSON_ID, P.NAME
HAVING COUNT(C.PERSON_ID) > 10
ORDER BY P.NAME;