WITH ACTOR AS (
SELECT C.TITLE_ID, C.PERSON_ID, P.NAME, P.BORN
FROM CREW AS C
JOIN PEOPLE AS P ON P.PERSON_ID = C.PERSON_ID
WHERE C.CATEGORY = "ACTOR" AND P.BORN <> 'NULL'),
ACTRESS AS (
SELECT C.TITLE_ID, C.PERSON_ID, P.NAME, P.BORN
FROM CREW AS C
JOIN PEOPLE AS P ON P.PERSON_ID = C.PERSON_ID
WHERE C.CATEGORY = "ACTRESS" AND P.BORN <> 'NULL')
SELECT DISTINCT A.BORN, A.NAME, B.NAME
FROM ACTOR AS A
JOIN ACTRESS AS B ON A.TITLE_ID = B.TITLE_ID AND A.BORN = B.BORN
ORDER BY A.BORN, A.NAME, B.NAME;
