SELECT DISTINCT P.NAME
FROM CREW AS C
LEFT JOIN PEOPLE AS P ON C.PERSON_ID = P.PERSON_ID
WHERE C.TITLE_ID IN (
SELECT TITLE_ID FROM CREW 
WHERE PERSON_ID IN (
SELECT PERSON_ID FROM PEOPLE WHERE NAME = 'JENNIFER LAWRENCE'))
ORDER BY P.NAME;