SELECT DISTINCT P.PNUMBER
FROM PROJECT AS P, EMPLOYEE AS E, DEPARTMENT AS D
WHERE P.DNUM = D.DNUMBER AND D.MGRSSN = E.SSN AND E.LNAME = 'WONG'
UNION
SELECT DISTINCT P.PNUMBER
FROM PROJECT AS P, EMPLOYEE AS E, WORKS_ON AS W
WHERE P.PNUMBER = W.PNO AND W.ESSN = E.SSN AND E.LNAME = 'WONG';