SELECT LNAME, FNAME FROM EMPLOYEE
WHERE NOT EXISTS (SELECT * FROM WORKS_ON AS B
WHERE( B.PNO IN (SELECT PNUMBER FROM PROJECT WHERE DNUM = 5))
AND
NOT EXISTS (SELECT * FROM WORKS_ON AS C 
WHERE C.ESSN = SSN AND C.PNO = B.PNO));